### ISSUE TITLE
Unable to specify scopes before sign in

### ISSUE THREAD

**Issue by dsharma** [google/GoogleSignIn-iOS#37] opened 2021-07-25 10:52 UTC
The new API looks to be a two step sign in -- first step basic sign in and then another one using addScopes to add a scope. This is a departure from previous versions of SDK where we could specify scopes as a property to GIDSignIn.sharedInstance() before sign in. Is this a new behaviour  or is it still possible to do single step sign in?

**Comment by petea** [comment] 2021-07-25 16:02
Duplicate of #23

**Closed** 2021-07-25 16:04 UTC
