### ISSUE TITLE
macOS app login using google was rejected

### ISSUE THREAD

**Issue by adrian920** [google/GoogleSignIn-iOS#412] opened 2024-05-10 06:43 UTC
The macOS app uses Google login, and now the submission for review has been rejected. The reason is: Guideline 4.0 - Design  The user is taken to the default web browser to sign in or register for an account, which provides a poor user experience. 
Can this problem be solved?

**Comment by mdmathias** [comment] 2024-05-10 15:33
@adrian920 please see https://github.com/google/GoogleSignIn-iOS/issues/388 for a discuss and how others have resolved this issue.

Closing this issue as a duplicate of https://github.com/google/GoogleSignIn-iOS/issues/388. Please follow along there.

**Closed by mdmathias** 2024-05-10 15:33 UTC
