### ISSUE TITLE
Support App Privacy Manifest

### ISSUE THREAD

**Issue by devssun** [google/GoogleSignIn-iOS#341] opened 2023-09-25 01:45 UTC
**Is your feature request related to a problem you're having? Please describe.**
Apple required App Privacy manifests until 2025. So GoogleSignIn-iOS SDK that contains an app privacy manifest must be signed.
I would like to know when you adopt this change.

References
https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/news/?id=av1nevon
https://developer.apple.com/app-store/user-privacy-and-data-use/

Please check it out. Thanks!

**Describe the solution you'd like**
Add Privacy Manifest

**Describe alternatives you've considered**

**Additional context**

**Comment by mdmathias** [comment] 2023-09-25 16:19
Thanks for the issue. We are tracking this internally and will address it in the Fall.

**Comment by devssun** [comment] 2023-09-26 00:25
Thank you for your comment.

**Comment by mdmathias** [comment] 2023-12-21 19:12
Wanted to post an update: we are planning to include add a privacy manifest prior to Apple's Spring 2024 deadline.

**Comment by lakshmankreditbee** [comment] 2024-01-16 07:48
Hi, when can we expect an update regarding this issue?

**Comment by mdmathias** [comment] 2024-01-16 18:20
We do not have an exact date planned for a new release that will add this manifest, but per [my last message here](https://github.com/google/GoogleSignIn-iOS/issues/341#issuecomment-1866807379), we will get this done prior to Apple's Spring 2024 deadline.

**Comment by mejim707** [comment] 2024-02-13 18:41
Hi, is there an update for timing on this release? We only have about 1.5 months before April and will need time to implement, resolve any potential breaking changes, and get sign off on this new release. 

Thanks

**Comment by mdmathias** [comment] 2024-02-13 18:53
Hi @mejim707 we are actively working on this, but we do not have a specific date to share. We do understand that folks depending upon GSI will need time, and are working as quickly as we can. Please stay tuned as we will be updating here as soon as possible.

**Comment by mejim707** [comment] 2024-02-13 18:58
Thank you sir!

**Comment by batikansosun** [comment] 2024-03-11 06:25
Hi @mdmathias, 

Would you please let me know if there has been any progress on this?

**Comment by mdmathias** [comment] 2024-03-11 15:39
We will be adding the privacy manifest and making a release in a couple of weeks, which should give developers time before the [May 1st date posted by Apple](https://developer.apple.com/news/?id=3d8a9yyh).

**Comment by Mcrich23** [comment] 2024-03-19 01:07
Hi @mdmathias I just wanted to mention that GTMAppAuth also is required to have a privacy manifest, and the current version used by GoogleSignIn-iOS does not support that version of GTMAppAuth.

**Comment by Mcrich23** [comment] 2024-03-19 01:16
I noticed that the latest changes in Main support GTMAppAuth 4.0.0 which has a manifest, but the current release (7.0.0) does not. Can you please provide insight into when those changes will be released?

**Comment by ywsang** [comment] 2024-03-19 01:25
We are actively working on prepping a new release that will update dependencies to versions that include a privacy manifest, as well as add a privacy manifest for GSI itself.

**Closed** 2024-03-22 16:14 UTC
Labels: enhancement, infra

**Comment by ywsang** [comment] 2024-03-22 22:21
@mejim707 Not quite yet, but we're working on getting a new release that includes the Privacy Manifest update soon.

**Comment by SeongWook-Jo** [comment] 2024-04-01 08:26
@ywsang If the issue is resolved, will Unity samples also be provided?

**Comment by ywsang** [comment] 2024-04-01 21:33
@SeongWook-Jo This issue is resolved and the release that includes in the Privacy Manifest has been made ([7.1.0](https://github.com/google/GoogleSignIn-iOS/releases/tag/7.1.0)). We don't have any actively maintained Unity samples (our existing samples written in Swift and iOS can be found [here](https://github.com/google/GoogleSignIn-iOS/tree/main/Samples)), and there are no plans to create a new set of Unity sample projects.

**Comment by Mcrich23** [comment] 2024-04-01 23:54
Also, this isn't something that devs have to touch other than updating the version

**Comment by SeongWook-Jo** [comment] 2024-04-02 02:49
@ywsang [Here](https://github.com/googlesamples/google-signin-unity), there's a sample provided previously for Unity. However, it's not being updated currently. As a result, many Unity developers might be experiencing difficulties. Is there an effective way to import that SDK into Unity?

**Comment by adorum** [comment] 2024-04-03 12:32
@vonovak regarding react-native-google-signin/google-signin#1265 release GoogleSignIn-iOS 7.1.0 is already out.

**Comment by mdmathias** [comment] 2024-04-03 22:48
@SeongWook-Jo We do not own those samples and do not have the expertise to update them. Perhaps you can reach out to that repo and make a request to update them there?
