### ISSUE TITLE
Request for Alamofire Dependency Update to Support Privacy Manifest in AlamofireObjectMapper

### ISSUE THREAD

**Issue by KKakadiyaKashyap** [google/GoogleSignIn-iOS#380] opened 2024-03-18 13:50 UTC
I'm currently using GoogleUtilities version 7.0.0 in my Swift project, which automatically includes GTMAppAuth (< 3.0, >= 1.3). However, I need to use GTMAppAuth version 4.1.1 due to its support for the 'Privacy Manifest', which is crucial for my project. Is there a way to update GoogleUtilities dependency to accommodate GTMAppAuth 4.1.1 , or could you suggest a workaround?
also need privacy manifest file to GoogleUtilities SDK.

**Comment by ywsang** [comment] 2024-03-18 19:41
Hi there! Could you point me towards the GoogleUtilities dependency on GTMAppAuth (< 3.0, >= 1.3)? Looking at GoogleUtilities's [podspec](https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities.podspec) or Swift [package](https://github.com/google/GoogleUtilities/blob/main/Package.swift), I don't see any dependency on GTMAppAuth.

If by chance "GoogleUtilities" is a typo and the issue is with GoogleSignIn-iOS, we're actively working on getting GoogleSignIn-iOS ready for Apple's Privacy Manifest requirement. This will include updating dependencies to versions that include Privacy Manifests, as well as adding a Privacy Manifest for GoogleSignIn-iOS. Follow https://github.com/google/GoogleSignIn-iOS/issues/341 for updates.

**Comment by zhangwei5436** [comment] 2024-03-21 06:32
need add Privacy Manifests  thanks

**Comment by zhangwei5436** [comment] 2024-03-25 08:20
I'm currently using GoogleSign version 7.0.0 in my Swift project, but it don't include Privacy Manifests ,please update 7.1.0

**Comment by zhangwei5436** [comment] 2024-03-25 08:44
I'm currently using GoogleSign version 7.0.0 in my Swift project,but ,it don't include Privacy Manifests,please update 7.1.0

**Comment by yasiraliraj** [comment] 2024-03-25 11:59
Hello Google Sign In Team,

I hope this message finds you well. I would like to draw your attention to an important update required by the App Store. Starting May 1, 2024, a privacy manifest will be mandatory for all apps. Given the ongoing development and support for your SDK, integrating this feature would be highly beneficial for ensuring compliance with the new App Store guidelines. This addition would greatly help developers like us in continuing to provide seamless services through our applications. We appreciate your attention to this matter and look forward to any updates you can provide.

Thank you for your continued support.

**Comment by ywsang** [comment] 2024-03-25 17:40
Hi all, we are currently working on releasing a new version that will have a Privacy Manifest included. This will be done soon, which should give developers time before the [May 1st date posted by Apple](https://developer.apple.com/news/?id=3d8a9yyh).

I'm closing this issue for now, since I believe the original poster meant to refer to GoogleSignIn instead of GoogleUtilities or Alamofire.

**Closed by ywsang** 2024-03-25 17:40 UTC
Labels: bug, triage

**Comment by KKakadiyaKashyap** [comment] 2024-04-03 14:25
when provide ?

**Comment by ywsang** [comment] 2024-04-03 16:44
@KKakadiyaKashyap GoogleSignIn has released [7.1.0](https://github.com/google/GoogleSignIn-iOS/releases/tag/7.1.0), which has a Privacy Manifest for GoogleSignIn and updates the library's dependencies to point to version that also have Privacy Manifests. 

There's no use of AlamofireObjectMapper or GoogleUtilities in the library source code, so I'm not sure what you're referring to in the original [issue](https://github.com/google/GoogleSignIn-iOS/issues/380#issue-2192277050).
