### ISSUE TITLE
Not Bulding for visionOs

### ISSUE THREAD

**Issue by victorwads** [google/GoogleSignIn-iOS#442] opened 2024-06-12 21:47 UTC
**Describe the bug**
Some problem with Build when using visionOs Target

**To Reproduce**
Add SwiftPackage [oogleSignIn-iOS](https://github.com/google/GoogleSignIn-iOS) to any project
import
add visionOs Native target (not design for iPad)
try to build

**Screenshots**
![image](https://github.com/google/GoogleSignIn-iOS/assets/20746587/527d38af-4a6a-40fe-ab10-b7f5ddf68441)

**Environment**
- Device: Xcode 16 
- OS: Macos Sequoia

**Comment by mdmathias** [comment] 2024-06-12 22:43
visionOS is not currently supported. Closing as a duplicate of https://github.com/google/GoogleSignIn-iOS/issues/353.

**Closed by mdmathias** 2024-06-12 22:43 UTC
Labels: bug, triage
