### ISSUE TITLE
Can not compile for visionOS

### ISSUE THREAD

**Issue by WillBishop** [google/GoogleSignIn-iOS#361] opened 2023-12-24 04:47 UTC
**Describe the bug**
Trying to compile this library for VisionOS results in a heap of errors.

**To Reproduce**
1. Create an new Xcode Project
2. Add this library as an SPM dependency
3. Add Apple Vision as a target (not the 'Made for iPad' variant, you need the native Apple Vision target).
4. Attempt to compile this library.

**Expected behavior**
I would like to see this library compiling for VisionOS as it's coming out soon and without this library apps the implement Google log in aren't able to test their apps.

**Screenshots**
<img width="602" alt="image" src="https://github.com/google/GoogleSignIn-iOS/assets/17292672/d31a36d1-80c9-452c-b44f-a3c4b2019081">

**Environment**
- Device: MacBook Pro M1 (Apple Vision Pro Simulator)
- OS: visionOS

**Comment by mdmathias** [comment] 2024-01-08 23:29
This is a duplicate of #353

**Closed by mdmathias** 2024-01-08 23:29 UTC
Labels: bug, triage
