### ISSUE TITLE
Some google accounts can't login, "500. That's an error."

### ISSUE THREAD

**Issue by Mioke** [google/GoogleSignIn-iOS#465] opened 2024-08-09 07:15 UTC
**Describe the bug**
Some of our users can't login using this SDK, it shows `500, That's an error.` without more detail. They helped to try to login in Chrome app and it can login as normal.

**To Reproduce**
I can't reproduce this issue, and the account holders can't share their accounts too.

**Expected behavior**
Can login as normal.

**Screenshots**
<img width="727" alt="SeaTalk_IMG_20240809_145551" src="https://github.com/user-attachments/assets/f8d2bdf9-eac9-4028-84ad-9786a591e667">

**Environment**
- Device: iPhone 13 Pro
- OS: iOS 17
- SDK Version: 7.1.0

**Comment by camden-king** [comment] 2024-08-09 18:31
@Mioke Thanks for reporting this! We haven't noticed this behavior on our side. Can you please provide reproduction steps so we can look into it further?

**Comment by woodmtw** [comment] 2024-08-11 05:05
I removed one of my gmail accounts from my iPhone 13 Pro Max and when trying to add the account back on I am getting the exact same error after entering my credentials. I am working fine on my iPad with that same gmail account and credentials. Have we discovered a new bug in the mail app?
![IMG_5893](https://github.com/user-attachments/assets/9c1eeaf0-debe-4f78-87fe-74a2c480a081)

**Comment by jpweytjens** [comment] 2024-08-11 09:45
Same issue here. Can log in to all Google apps on iOS 17.5.1 and can log in to Google services in multiple browsers (Safari, Chrome, ...). Only when adding a Google account via the iOS settings, do I bump into the 500 error. The 500 error occurs after succesfully filling the password and 2FA authentication.

Opening the log in popup of the iOS settings menu in Chrome or any other browser doesn't help.

**Comment by woodmtw** [comment] 2024-08-11 12:11
I did a restore from backup of my iPhone from a few months ago using iMazing, but this did not fix my problem. I have also cleared my Safari browser cache and history with no success. Went into iPhone settings and made Edge my default browser, instead of Safari, and tried again with no luck. This is not good as I have hundreds of contacts in my gmail account that I cannot get back on my iPhone until I am able to add my gmail account back on my iPhone. Guess I'll try to open a ticket with Apple Support.

**Comment by Mioke** [comment] 2024-08-12 02:41
@camden-king Sorry I can't reproduce this issue too, there only a few of users of our app are facing this problem. But is there any advice for users to collect more error information? I can ask them for help.

**Comment by woodmtw** [comment] 2024-08-12 17:30
...quick update. I had two other gmail accounts on my iPhone 13 Pro Max and I removed them as well. When trying to add back any one of the 3 gmail accounts into my native iPhone "Mail" app, they all fail with this same "500. That's an error." message. I haven't tried to remove them from my iPad as I don't want to be completely unable to access my email.

**Comment by ywsang** [comment] 2024-08-12 19:14
@Mioke Any additional information they can provide about their sign-in attempt could be helpful: was it the first sign-in attempt or had the account successfully signed-in before? Was access to additional scopes granted? etc. Does updating the phone's OS to the latest version (iOS 17.6.1) help? Furthermore, if it's possible, any stack traces or a full screen recording of the sign-in flow resulting in the 500 error could help us debug. Without being able to repro the error ourselves, we unfortunately can't help much.

**Comment by ywsang** [comment] 2024-08-12 19:18
Hi @woodmtw @jpweytjens! The GoogleSignIn-iOS SDK maintained in this GitHub repo deals with using a Google account to sign into a 3rd party app. Signing in via iOS Settings or the native "Mail" app doesn't use the GoogleSignIn-iOS SDK, so we can't offer much help. I'd suggest making sure your phone's OS is up-to-date and trying again, but otherwise it seems the issues you're experiencing are unrelated to GoogleSignIn-iOS.

**Comment by Mioke** [comment] 2024-08-13 01:46
Add more information: 
only appears on iPhone with the same account, a user help to try on an Android device and it works fine. So it seams only occurs on specific accounts with the iOS SDK. 

So the behavior is:
on the same iPhone and using mail app and chrome app: can login.
the same account and using the same our app on another Android phone: can login.
only using the account on any iPhone: can't login.

He tried to use an old version of my app with an old Google-SignIn SDK, also can't login so may be this's not related to the SDK version.

The screen record:
https://github.com/user-attachments/assets/2674cfee-7b0e-44c5-b0cd-8b2d4f967a8c

**Comment by woodmtw** [comment] 2024-08-13 15:33
I just upgraded my IOS to 17.6.1 and can now add gmail accounts to my Mail app.  Looks like they found a bug in the previous code and fixed it!

**Comment by ywsang** [comment] 2024-08-13 23:07
@Mioke Thanks! Would you also be able to ask the user to provide any specifics about the sign-in attempt (for example, had the account signed in before? If yes, what's the reasoning to having to sign again? -- did the account disconnect and/or sign out, or had the account removed your app's access via [Manage third-party connections](https://support.google.com/accounts/answer/13533235?hl=en#zippy=%2Csign-in-with-google) before trying to sign in again?, etc). 

In addition, would you be able to provide info about your GoogleSignIn configuration and which API method you're calling to trigger sign-in?

In general, any information that could help us replicate the scenario (and then hopefully be able to repro the issue) would be helpful.

**Comment by woodmtw** [comment] 2024-08-14 04:00
@ywsang  If you are asking me, I have had 3 Gmail accounts set up on my iPhone for over 2 years and had not had any trouble. I started having trouble with one of my Gmail accounts asking for a password and wasn't able to get it to accept it. I decided to remove that Gmail account from my iPhone and then re-add it. This is when I discovered I couldn't get past the "500. That' an error. That's all we know." message after providing my credentials. My iPad and PC continued to work fine with all 3 Gmail accounts. During troubleshooting, I decided to restore my phone from a backup from about 6 months ago. That didn't work because the IOS version wasn't reverted to during that process. I was running and continued to run v17.5.1 after the restore and still had the same error. I then deleted the other two Gmail accounts from my phone and couldn't add either one of those back in either. Only after upgrading my IOS to v17.6.1 was I able to re-add all 3 Gmail accounts.  Hope that helps..

**Comment by Mioke** [comment] 2024-08-14 09:46
Hi @ywsang thanks for your reply.

Most of the users have this problem are new Google account users, but there is a user that he is our app admin and he wants to test the login flow, so he signed out the app and try to sign in again then found out he can't do it either. He helps to check the [Manage third-party connections](https://support.google.com/accounts/answer/13533235?hl=en#zippy=%2Csign-in-with-google) page and it shows as normal.

For additional context, this problem started last week—though we're not sure of the exact time—and we hadn't received any reports of this issue prior to then.

The GoogleSignIn configuration is simple:
```swift
let configuration = GIDConfiguration(clientID: clientID)        
GIDSignIn.sharedInstance.configuration = configuration
```

The API calling code:
```swift
GIDSignIn.sharedInstance.signIn(withPresenting: viewController, hint:emailAddress) { signInResult, error in
    // handle result 
}
```

handling the redirection:
```swift
func handleApplication(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
    return GIDSignIn.sharedInstance.handle(url)
}
    
func handleApplication(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    return GIDSignIn.sharedInstance.handle(url)
}
```

**Comment by Mioke** [comment] 2024-08-15 02:36
The issue we encountered should have just been resolved within the last hours, and users who experienced the problem can now log in normally. So it seems like this issue was related to the service.

**Comment by ywsang** [comment] 2024-08-15 16:40
@Mioke glad to hear! Closing this issue now. Feel free to reach back out if the issue comes back.

**Closed by ywsang** 2024-08-15 16:40 UTC
Labels: bug
