### ISSUE TITLE
Failed Archive

### ISSUE THREAD

**Issue by YesidMarin** [google/GoogleSignIn-iOS#321] opened 2023-06-26 23:37 UTC
Hello

I'm experiencing an issue when archiving the project. I'm getting a "No such file or directory" error. I'm using Swift Package Manager.

<img width="702" alt="image" src="https://github.com/google/GoogleSignIn-iOS/assets/29234631/978ff974-642a-4033-84b2-0316537ead70">

**Comment by mdmathias** [comment] 2023-06-27 00:42
Hi @YesidMarin. In the future, please follow our [issue template for filing a bug](https://github.com/google/GoogleSignIn-iOS/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). It will help us identify problems and resolutions more quickly.

I'm not able to reproduce this issue. I created a new test app. Added GoogleSignIn-iOS version 7.0.0 via Swift Package Manager, added a sign in button from the library, and was able to build and run. I was also able to Archive the sample app.

I suspect that this has something to do with your project's set up and am resolving this as not reproducible. Please reopen and supply details (i.e., reproduction steps, links your broken project if possible, etc.) if indeed this issue can be fixed within the repo.

Good luck!

**Closed by mdmathias** 2023-06-27 00:42 UTC
Labels: bug
