### ISSUE TITLE
How to downlaod GoogleSignIn with framework ？

### ISSUE THREAD

**Issue by kobe1941** [google/GoogleSignIn-iOS#390] opened 2024-04-07 08:03 UTC
we do not need source code，we use google sign in with framework，how can i to upgrade our googleSignIn framework?

**Comment by mdmathias** [comment] 2024-04-09 16:40
Duplicate of https://github.com/google/GoogleSignIn-iOS/issues/61

**Closed by mdmathias** 2024-04-09 16:40 UTC
Labels: enhancement, triage
