### ISSUE TITLE
Need Privacy Manifest

### ISSUE THREAD

**Issue by kalsariyarahul** [google/GoogleSignIn-iOS#362] opened 2024-01-02 06:36 UTC
Need Privacy Manifest

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by mdmathias** [comment] 2024-01-03 21:52
Duplicate of https://github.com/google/GoogleSignIn-iOS/issues/341

**Closed by mdmathias** 2024-01-03 21:52 UTC
Labels: enhancement, triage
