### ISSUE TITLE
PrivacyInfo manifest support

### ISSUE THREAD

**Issue by iOSyifeng** [google/GoogleSignIn-iOS#384] opened 2024-03-21 09:12 UTC
后续会支持PrivacyInfo manifest嘛  在苹果公布的三方SDK中有谷歌登录

**Comment by ywsang** [comment] 2024-03-21 16:53
Duplicate of https://github.com/google/GoogleSignIn-iOS/issues/341

We're actively working on Privacy Manifest support. Follow #341 for updates.

**Closed by ywsang** 2024-03-21 16:53 UTC
Labels: enhancement, triage
