### ISSUE TITLE
Requesting the Google Sign In SDK in xcframework.

### ISSUE THREAD

**Issue by phillip5094** [google/GoogleSignIn-iOS#391] opened 2024-04-08 00:26 UTC
Due to our development environment constraints, we are unable to use CocoaPods or SPM. 
Therefore, we need to utilize the Google Sign In SDK in xcframework. 
We kindly request the functionality to download the xcframework.

**Comment by mdmathias** [comment] 2024-04-09 16:40
Duplicate of https://github.com/google/GoogleSignIn-iOS/issues/61

**Closed by mdmathias** 2024-04-09 16:40 UTC
Labels: enhancement, triage
