### ISSUE TITLE
Signing for "GoogleSignIn-GoogleSignIn" requires a development team 

### ISSUE THREAD

**Issue by GRyabkin** [google/GoogleSignIn-iOS#223] opened 2022-09-20 12:31 UTC
I have an error when use GoogleSign-In pod

"Signing for "GoogleSignIn-GoogleSignIn" requires a development team "

I can change it manually in Pods but in that case build machine on CI fails to run

P.S. I currently have this workaround in place:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
  end
end
```

Not sure that the fix is robust enough. Could you add a change in your .podspec file or build settings please?

**Comment by petea** [comment] 2022-10-26 23:19
Duplicate of #105

**Closed by petea** 2022-10-26 23:19 UTC
